package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class testController {
	@FXML
	private CheckBox checkID;
	@FXML
	private CheckBox checkName;
	@FXML
	private CheckBox checkAge;
	@FXML
	private CheckBox checkGender;
	@FXML
	private CheckBox checkClass;
	@FXML
	private CheckBox checkDepartment;
	@FXML
	private CheckBox checkAdress;
	@FXML
	private TextField ID;
	@FXML
	private TextField Name;
	@FXML
	private TextField infAge;
	@FXML
	private TextField Gender;
	@FXML
	private TextField Class;
	@FXML
	private TextField Department;
	@FXML
	private TextField Address;
	@FXML
	private TextField supAge;
	@FXML
	private Button inqButton;
	@FXML
	private TextField statement;
	@FXML
	private TableView result;
	@FXML
	private TableColumn csid;
	@FXML
	private TableColumn csname;
	@FXML
	private TableColumn csage;
	@FXML
	private TableColumn cssex;
	@FXML
	private TableColumn cclass;
	@FXML
	private TableColumn cdepartment;
	@FXML
	private TableColumn caddress;

	// Event Listener on Button[#inqButton].onAction
	@FXML
	public void inquireAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#inqButton].onMouseClicked
	@FXML
	public void clickInquire(MouseEvent event) {
		// TODO Autogenerated
	}
}
